### ISSUE TITLE
Consider asymmetrical use cases of serial-forms

### ISSUE THREAD

**Issue by phalt** [mjtamlyn/django-serial-forms#13]
Some use cases for DRF serializers are different dependant on the use case.

For example:

User Input:
- Validating and cleaning input data

Service output:
- serialising model instances into external representations for particular views (without validation or cleaning)
- Providing modular representational "components" for use in various views and templates.

As a lot of people use DRF serializers to reduce richer objects to a simple set of key/values, often with different keys or computed values to their internal equivalent, this use case can bring a lot of value to serial-forms and replace the current use of DRF serializers, which arguably isn't quite the right tool for the job.

**Comment by MoritzS** [comment]
Serial forms definitely handle both use cases and neither of them are afterthoughts but we take both into account when designing the architecture and API. See also #3.
