### ISSUE TITLE
Consider "Representation" naming.

### ISSUE THREAD

**Issue by phalt** [mjtamlyn/django-serial-forms#14]
This is linked to #13.

Naming is the key thing here, I believe we want to provide toolsets that make providing flattened representations of things to the view layer easy to understand. "forms" and "serializers" don't always provide this context so well.

This could be a way where we're able to define the difference between the asymmetrical use cases.

**Comment by mjtamlyn** [comment]
Agreed, naming things is also hard. `Shaper` is another name I've got knocking around. See #15 for some discussion of what the output of this layer is "allowed" to be.
